config/routes.rb
Rails.application.routes.draw do
  resources :flights
  resources :aircrafts
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "aircrafts#index"

  resources :aircrafts do
    resources :flights do
      collection do
        post :import
      end
    end
  end
  
end

app/models/aircraft.rb
class Aircraft < ApplicationRecord
  has_many :engines, dependent: :destroy
  has_many :flights, dependent: :destroy
  has_one :annunal, dependent: :destroy
  has_one :hundred_hour, dependent: :destroy
  has_one :hobbs, dependent: :destroy
  has_one :elt, dependent: :destroy
  has_one :vor, dependent: :destroy
  has_one :pitot, dependent: :destroy
  has_one :purchase, dependent: :destroy

  validates :tail, presence: true
  validates :year, presence: true
  validates :make, presence: true
  validates :model, presence: true
  validates :serial, presence: true
  validates :tt, presence: true

  def to_s
    "#{self.tail} - #{self.year} #{self.make} #{self.model}"
  end
  
end

app/controllers/aircrafts_controller.rb
class AircraftsController < ApplicationController
  before_action :set_aircraft, only: %i[ show edit update destroy ]

  # GET /aircrafts or /aircrafts.json
  def index
    @aircrafts = Aircraft.all
  end

  # GET /aircrafts/1 or /aircrafts/1.json
  def show
  end

  # GET /aircrafts/new
  def new
    @aircraft = Aircraft.new
  end

  # GET /aircrafts/1/edit
  def edit
  end

  # POST /aircrafts or /aircrafts.json
  def create
    @aircraft = Aircraft.new(aircraft_params)

    respond_to do |format|
      if @aircraft.save
        format.html { redirect_to aircraft_url(@aircraft), notice: "Aircraft was successfully created." }
        format.json { render :show, status: :created, location: @aircraft }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @aircraft.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /aircrafts/1 or /aircrafts/1.json
  def update
    respond_to do |format|
      if @aircraft.update(aircraft_params)
        format.html { redirect_to aircraft_url(@aircraft), notice: "Aircraft was successfully updated." }
        format.json { render :show, status: :ok, location: @aircraft }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @aircraft.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /aircrafts/1 or /aircrafts/1.json
  def destroy
    @aircraft.destroy

    respond_to do |format|
      format.html { redirect_to aircrafts_url, notice: "Aircraft was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_aircraft
      @aircraft = Aircraft.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def aircraft_params
      params.require(:aircraft).permit(:tail, :make, :model, :year, :serial, :tt)
    end
end

app/helpers/aircrafts_helper.rb
module AircraftsHelper
end

app/views/aircrafts/_aircraft.html.erb
<div id="<%= dom_id aircraft %>">
  <p>
    <strong>Tail:</strong>
    <%= aircraft.tail %>
  </p>

  <p>
    <strong>Make:</strong>
    <%= aircraft.make %>
  </p>

  <p>
    <strong>Model:</strong>
    <%= aircraft.model %>
  </p>

  <p>
    <strong>Year:</strong>
    <%= aircraft.year %>
  </p>

  <p>
    <strong>Serial:</strong>
    <%= aircraft.serial %>
  </p>

  <p>
    <strong>Tt:</strong>
    <%= aircraft.tt %>
  </p>

  <p>
    <strong>Flight Time:</strong>
    <%= aircraft.flights.sum(&:time) %>
  </p>

  <p>
    <strong>Fuel:</strong>
    <%= aircraft.flights.sum(&:fuel) %>
  </p>

  <p>
    <strong>Oil:</strong>
    <%= aircraft.flights.sum(&:oil) %>
  </p>

  <%= link_to :flights, [aircraft, :flights]%>

</div>

app/views/aircrafts/_form.html.erb
<%= form_with(model: aircraft) do |form| %>
  <% if aircraft.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(aircraft.errors.count, "error") %> prohibited this aircraft from being saved:</h2>

      <ul>
        <% aircraft.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :tail, style: "display: block" %>
    <%= form.text_field :tail %>
  </div>

  <div>
    <%= form.label :make, style: "display: block" %>
    <%= form.text_field :make %>
  </div>

  <div>
    <%= form.label :model, style: "display: block" %>
    <%= form.text_field :model %>
  </div>

  <div>
    <%= form.label :year, style: "display: block" %>
    <%= form.number_field :year %>
  </div>

  <div>
    <%= form.label :serial, style: "display: block" %>
    <%= form.text_field :serial %>
  </div>

  <div>
    <%= form.label :tt, style: "display: block" %>
    <%= form.text_field :tt %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/aircrafts/edit.html.erb
<h1>Editing aircraft</h1>

<%= render "form", aircraft: @aircraft %>

<br>

<div>
  <%= link_to "Show this aircraft", @aircraft %> |
  <%= link_to "Back to aircrafts", aircrafts_path %>
</div>

app/views/aircrafts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Aircraft</h1>

<div id="aircrafts">
  <% @aircrafts.each do |aircraft| %>
    <p>
      <%= link_to aircraft.to_s, aircraft %>
    </p>
  <% end %>
</div>

<%= link_to "New aircraft", new_aircraft_path %>

app/views/aircrafts/new.html.erb
<h1>New aircraft</h1>

<%= render "form", aircraft: @aircraft %>

<br>

<div>
  <%= link_to "Back to aircrafts", aircrafts_path %>
</div>

app/views/aircrafts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @aircraft %>

<br/>

<div>
  <%= link_to "Edit this aircraft", edit_aircraft_path(@aircraft) %> |
  <%= link_to "Back to aircrafts", aircrafts_path %>

  <br/>
  <br/>

  <%= button_to "Destroy this aircraft", @aircraft, method: :delete %>
</div>