config/routes.rb
Rails.application.routes.draw do
  resources :flights
  resources :aircrafts
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "aircrafts#index"

  resources :aircrafts do
    resources :flights do
      collection do
        post :import
      end
    end
  end
  
end

app/models/flight.rb
class Flight < ApplicationRecord
  belongs_to :aircraft

  validates :date, presence: true
  validates :from, presence: true
  validates :to, presence: true
  validates :oil, presence: true
  validates :fuel, presence: true
  validates :tach, presence: true
  validates :hobbs, presence: true

  after_update :update_aircraft

  scope :thirty_days, -> { where('date >= ?', Time.now - 30.days) }
  scope :month, -> { where('date >= ?', Time.now - 1.month) }
  scope :three_months, -> { where('date >= ?', Time.now - 3.month) }
  scope :year, -> { where('date >= ?', Time.now - 1.year) }
  scope :tach, ->(tach) { where('tach >= ?', tach) }
    
  # Return a human readbale string
  def to_s
    "#{self.date.to_s} - #{self.from} #{self.to}" 
  end

  # Return the next flight
  def next
    aircraft.flights.where("id > ?", id).first
  end

  # Returns the previous flight
  def prev
    aircraft.flights.where("id < ?", id).last
  end

  # Returns the time for a flight
  def time
    return 0 if self.prev.nil?

    time = (self.hobbs - self.prev.hobbs).round(1) 
    return time unless time <= 0

    (self.tach - self.prev.tach).round(1)
  end

  # Update aircraft times & oil
  def update_aircraft
    t = (tach - prev.tach).round(1)

    # TODO update aircraft TT with increase of tach time
    # TODO update aircraft engine with tach time
    # TODO update oil_change with added oil
    if aircraft.engine.tach < tach
      aircraft.tt = aircraft.tt + t
      aircraft.engine.tach = aircraft.engine.tach
      aircraft.save
    end

    aircraft.engine.oil_change.added = aircraft.engine.oil_change.added + oil
    aircraft.engine.oil_change.save
  end

end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  before_action :set_flight, only: %i[ show edit update destroy ]

  # GET /flights or /flights.json
  def index
    @aircraft = Aircraft.find(params[:aircraft_id])
    @flights = @aircraft.flights
  end

  # GET /flights/1 or /flights/1.json
  def show
  end

  # GET /flights/new
  def new
    @flight = Flight.new
  end

  # GET /flights/1/edit
  def edit
  end

  # POST /flights or /flights.json
  def create
    @flight = Flight.new(flight_params)

    respond_to do |format|
      if @flight.save
        format.html { redirect_to flight_url(@flight), notice: "Flight was successfully created." }
        format.json { render :show, status: :created, location: @flight }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @flight.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /flights/1 or /flights/1.json
  def update
    respond_to do |format|
      if @flight.update(flight_params)
        format.html { redirect_to flight_url(@flight), notice: "Flight was successfully updated." }
        format.json { render :show, status: :ok, location: @flight }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @flight.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /flights/1 or /flights/1.json
  def destroy
    @flight.destroy

    respond_to do |format|
      format.html { redirect_to flights_url, notice: "Flight was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  # IMPORT flights
  def import
    return redirect_to request.referer, notice: :no_file if params[:file].nil?
    return redirect_to request.referer, notice: :only_csv unless params[:file].content_type == 'text/csv'

    CsvImportService.new.call(params)

    redirect_to request.referer, notice: t(:import_started)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_flight
      @flight = Flight.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def flight_params
      params.require(:flight).permit(:aircraft_id, :date, :from, :to, :oil, :fuel, :tach, :hobbs, :note)
    end
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/views/flights/_flight.html.erb
<div id="<%= dom_id flight %>">
  <p>
    <strong>Aircraft:</strong>
    <%= link_to flight.aircraft.tail, flight.aircraft %>
  </p>

  <p>
    <strong>Date:</strong>
    <%= flight.date %>
  </p>

  <p>
    <strong>From:</strong>
    <a href="https://skyvector.com/airport/<%= flight.from %>"><%= flight.from %></a>
  </p>

  <p>
    <strong>To:</strong>
    <a href="https://skyvector.com/airport/<%= flight.to %>"><%= flight.to %></a>
  </p>

  <p>
    <strong>Oil:</strong>
    <%= flight.oil %>
  </p>

  <p>
    <strong>Fuel:</strong>
    <%= flight.fuel %>
  </p>

  <p>
    <strong>Tach:</strong>
    <%= flight.tach %>
  </p>

  <p>
    <strong>Hobbs:</strong>
    <%= flight.hobbs %>
  </p>

  <p>
    <strong>Note:</strong>
    <%= flight.note %>
  </p>

  <p>
    <strong>Flight Time:</strong>
    <%= flight.time  %>
  </p>

</div>

app/views/flights/_form.html.erb
<%= form_with(model: flight) do |form| %>
  <% if flight.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(flight.errors.count, "error") %> prohibited this flight from being saved:</h2>

      <ul>
        <% flight.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :aircraft_id, style: "display: block" %>
    <%= form.text_field :aircraft_id %>
  </div>

  <div>
    <%= form.label :date, style: "display: block" %>
    <%= form.date_field :date %>
  </div>

  <div>
    <%= form.label :from, style: "display: block" %>
    <%= form.text_field :from %>
  </div>

  <div>
    <%= form.label :to, style: "display: block" %>
    <%= form.text_field :to %>
  </div>

  <div>
    <%= form.label :oil, style: "display: block" %>
    <%= form.number_field :oil %>
  </div>

  <div>
    <%= form.label :fuel, style: "display: block" %>
    <%= form.number_field :fuel, step: 0.1, max: 99999.9, min: 0 %>
  </div>

  <div>
    <%= form.label :tach, style: "display: block" %>
    <%= form.number_field :tach, step: 0.1, max: 99999.9, min: 0 %>
  </div>

  <div>
    <%= form.label :hobbs, style: "display: block" %>
    <%= form.number_field :hobbs, step: 0.1, max: 99999.9, min: 0 %>
  </div>

  <div>
    <%= form.label :note, style: "display: block" %>
    <%= form.text_field :note %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/flights/_import.html.erb
<%= form_tag import_aircraft_flights_path, method: :post, multipart: true do %>
  <%= file_field_tag :file, accept: ".csv" %>
  <%= submit_tag :import %>
<% end %>

app/views/flights/edit.html.erb
<h1>Editing flight</h1>

<%= render "form", flight: @flight %>

<br>

<div>
  <%= link_to "Show this flight", @flight %> |
  <%= link_to "Back to flights", [@flight.aircraft, :flights]%>
</div>

app/views/flights/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Flights for <%= @aircraft.tail %></h1>

<div id="flights">
  <% @flights.each do |flight| %>
    <p>
      <%= link_to flight.to_s , flight %>
    </p>
  <% end %>
</div>

<%= render "import" %>

app/views/flights/new.html.erb
<h1>New flight</h1>

<%= render "form", flight: @flight %>

<br>

<div>
  <%= link_to "Back to flights", flights_path %>
</div>

app/views/flights/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @flight %>

<div>
  <%= link_to_if @flight.prev, "Previous", @flight.prev %> |
  <%= link_to_if @flight.next, "Next", @flight.next%>
</div>

<br/>

<div>
  <%= link_to "Edit this flight", edit_flight_path(@flight) %> |
  <%= link_to "Back to Flights", [@flight.aircraft, :flights]%>

  <br/>
  <br/>

  <%= button_to "Destroy this flight", @flight, method: :delete %>
</div>